# Site settings
title: Tingaloo's Bulb
email: ting.lew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A cool blog to understand web dev, and other stuff
baseurl: "/blog" # "/blog" for github, "" for local
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: tingGaLoo
github_username:  tingaloo

# Build settings
markdown: kramdown
kramdown:
  input: GFM

paginate: 5
